services:
  app:
    container_name: geonames_app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "mkdir -p /var/www/storage/logs /var/www/bootstrap/cache &&
             chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
             chmod -R ug+rwx /var/www/storage /var/www/bootstrap/cache &&
             apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - mongo
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - MONGODB_URI=mongodb://root:example@mongo:27017
      - MONGODB_DATABASE=geonames
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  mongo:
    container_name: geonames_mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  mongo_data:
