version: '3'
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
    depends_on:
       - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example